In [1]:
import pandas as pd 
data = [
    {'Name': 'Israel', 'Age': 16, 'Course':'Computer Science'},
    {'Name': 'Dayo', 'Age': 19, 'Course':'Animal Science'},
    {'Name': 'Bisola', 'Age': 14, 'Course':'Chemistry'}
]
df = pd.DataFrame(data)
print(df)

     Name  Age            Course
0  Israel   16  Computer Science
1    Dayo   19    Animal Science
2  Bisola   14         Chemistry

In [56]:
df.Name

0    Israel
1    Bisola
Name: Name, dtype: object

In [38]:
df.loc[0,'Age']

np.int64(16)

In [40]:
df.at[0,'Age']

np.int64(16)

In [42]:
df.iat[0,1]

np.int64(16)

In [ ]:
df.iloc[0,0:2]

pandas.core.frame.DataFrame

In [47]:
df
df.drop(1,axis=0, inplace=True)

In [48]:
df

     Name  Age            Course
0  Israel   16  Computer Science
2  Bisola   14         Chemistry

In [53]:
df =df.reset_index()

In [54]:
df

   index    Name  Age            Course
0      0  Israel   16  Computer Science
1      2  Bisola   14         Chemistry